seed: 42
epochs: 100
batch_size: 64
lr: 0.001
hidden_dims: [150, 150, 150]
activation: relu
train_ratio: 0.8
early_stop_patience: 50
scheduler:
  type: CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2
  eta_min: 0.000001
  warmup_epochs: 5
