wandb_project: verdict_benchmark
wandb_run_name: transformer_official

seed: 42
epochs: 400
batch_size: 16
lr: 0.0003
weight_decay: 0.0001
train_ratio: 0.8
early_stop_patience: 40

scheduler:
  type: CosineAnnealingWarmRestarts
  T_0: 15
  T_mult: 2
  eta_min: 0.000001
  warmup_epochs: 5

data:
  mat_path: D:/AiProjects/UCLmaster/dlfitting_verdict/VERDICT_training/AS_Z_fixdv/TrainingSet.mat

model:
  type: transformer
  class_name: TransformerRegressor
  params:
    d_model: 64
    nhead: 4
    num_layers: 2
    dim_feedforward: 128
    activation: relu
    dropout: 0.1
