wandb_project: verdict_benchmark
wandb_run_name: vae_regressor_official

seed: 42
epochs: 400
batch_size: 16
lr: 0.0003
weight_decay: 0.0001
train_ratio: 0.8
early_stop_patience: 40

scheduler:
  type: CosineAnnealingWarmRestarts
  T_0: 15
  T_mult: 2
  eta_min: 0.000001
  warmup_epochs: 5

data:
  mat_path: D:/AiProjects/UCLmaster/dlfitting_verdict/VERDICT_training/AS_Z_fixdv/TrainingSet.mat

model:
  type: vae_regressor
  class_name: VAERegressor
  params:
    latent_dim: 32
    hidden_dims: [128, 64]
    activation: relu
    dropout: 0.1
    beta: 0.1  # KL weight
    alpha: 0.5  # Reconstruction weight
